create table if not exists public.nextasx_guest_shares (
 id bigint generated by default as identity primary key,
 task_id bigint not null references public.s2_tasks(id) on delete cascade,
 token_hash text not null unique,
 pin_hash text not null,
 created_by bigint references public.s2_team_members(id) on delete set null,
 created_by_name text not null,
 expires_at timestamptz not null,
 revoked_at timestamptz,
 pin_failures integer not null default 0,
 locked_until timestamptz,
 created_at timestamptz not null default now()
);
create index if not exists nextasx_guest_shares_task_idx on public.nextasx_guest_shares(task_id);
create index if not exists nextasx_guest_shares_created_by_idx on public.nextasx_guest_shares(created_by);
alter table public.nextasx_guest_shares enable row level security;
revoke all on public.nextasx_guest_shares from anon, authenticated, public;

create table if not exists public.nextasx_guest_sessions (
 token_hash text primary key,
 share_id bigint not null references public.nextasx_guest_shares(id) on delete cascade,
 guest_name text not null,
 expires_at timestamptz not null,
 created_at timestamptz not null default now()
);
create index if not exists nextasx_guest_sessions_share_idx on public.nextasx_guest_sessions(share_id);
alter table public.nextasx_guest_sessions enable row level security;
revoke all on public.nextasx_guest_sessions from anon, authenticated, public;

create or replace function public.nextasx_create_guest_share(p_token text,p_admin_code text,p_task_id bigint,p_share_token text,p_pin text,p_expires_at timestamptz)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_member public.s2_team_members; v_author text; v_row public.nextasx_guest_shares;
begin
 if p_token is not null and p_token<>'' then
  select m.* into v_member from public.nextasx_member_sessions s join public.s2_team_members m on m.id=s.member_id
  where s.token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and s.expires_at>now();
 end if;
 if v_member.id is not null then v_author:=v_member.name;
 elsif p_admin_code='6387' then v_author:='Administrator';
 else raise exception 'Unauthorized'; end if;
 if p_pin !~ '^[0-9]{4,6}$' then raise exception 'PIN must be 4 to 6 digits'; end if;
 if p_expires_at<=now() or p_expires_at>now()+interval '180 days' then raise exception 'Invalid expiration'; end if;
 if not exists(select 1 from public.s2_tasks where id=p_task_id) then raise exception 'Task not found'; end if;
 insert into public.nextasx_guest_shares(task_id,token_hash,pin_hash,created_by,created_by_name,expires_at)
 values(p_task_id,encode(extensions.digest(p_share_token,'sha256'),'hex'),extensions.crypt(p_pin,extensions.gen_salt('bf')),v_member.id,v_author,p_expires_at)
 returning * into v_row;
 return jsonb_build_object('id',v_row.id,'expires_at',v_row.expires_at,'created_by_name',v_row.created_by_name);
end $$;

create or replace function public.nextasx_revoke_guest_share(p_token text,p_admin_code text,p_share_id bigint)
returns boolean language plpgsql security definer set search_path=''
as $$
declare v_ok boolean:=false;
begin
 if p_token is not null and p_token<>'' then
  v_ok:=exists(select 1 from public.nextasx_member_sessions where token_hash=encode(extensions.digest(p_token,'sha256'),'hex') and expires_at>now());
 end if;
 if not v_ok and p_admin_code='6387' then v_ok:=true; end if;
 if not v_ok then raise exception 'Unauthorized'; end if;
 update public.nextasx_guest_shares set revoked_at=now() where id=p_share_id;
 delete from public.nextasx_guest_sessions where share_id=p_share_id;
 return found;
end $$;

create or replace function public.nextasx_guest_login(p_share_token text,p_pin text,p_guest_name text,p_session_token text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_share public.nextasx_guest_shares; v_exp timestamptz;
begin
 select * into v_share from public.nextasx_guest_shares where token_hash=encode(extensions.digest(p_share_token,'sha256'),'hex');
 if v_share.id is null or v_share.revoked_at is not null or v_share.expires_at<=now() then raise exception 'Share link is unavailable or expired'; end if;
 if v_share.locked_until is not null and v_share.locked_until>now() then raise exception 'Too many attempts. Try again later'; end if;
 if extensions.crypt(p_pin,v_share.pin_hash)<>v_share.pin_hash then
  update public.nextasx_guest_shares set pin_failures=pin_failures+1,locked_until=case when pin_failures+1>=8 then now()+interval '15 minutes' else null end where id=v_share.id;
  raise exception 'Incorrect PIN';
 end if;
 if length(trim(p_guest_name))<2 or length(trim(p_guest_name))>80 then raise exception 'Enter your name'; end if;
 update public.nextasx_guest_shares set pin_failures=0,locked_until=null where id=v_share.id;
 v_exp:=least(v_share.expires_at,now()+interval '7 days');
 insert into public.nextasx_guest_sessions(token_hash,share_id,guest_name,expires_at)
 values(encode(extensions.digest(p_session_token,'sha256'),'hex'),v_share.id,trim(p_guest_name),v_exp);
 return jsonb_build_object('ok',true,'guest_name',trim(p_guest_name),'expires_at',v_exp);
end $$;

create or replace function public.nextasx_guest_task(p_session_token text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_session public.nextasx_guest_sessions; v_share public.nextasx_guest_shares; v_task public.s2_tasks;
begin
 select * into v_session from public.nextasx_guest_sessions where token_hash=encode(extensions.digest(p_session_token,'sha256'),'hex') and expires_at>now();
 if v_session.share_id is null then raise exception 'Guest session expired'; end if;
 select * into v_share from public.nextasx_guest_shares where id=v_session.share_id and revoked_at is null and expires_at>now();
 if v_share.id is null then raise exception 'Share link is unavailable or expired'; end if;
 select * into v_task from public.s2_tasks where id=v_share.task_id;
 return jsonb_build_object(
  'guest_name',v_session.guest_name,
  'task',jsonb_build_object('id',v_task.id,'title',v_task.title,'description',v_task.description,'assignee',v_task.assignee,'category',v_task.category,'location',v_task.location,'priority',v_task.priority,'status',v_task.status,'due_date',v_task.due_date),
  'checklist',coalesce((select jsonb_agg(jsonb_build_object('id',id,'body',body,'is_complete',is_complete,'completed_by_name',completed_by_name,'completed_at',completed_at) order by position,id) from public.nextasx_task_checklist where task_id=v_task.id),'[]'::jsonb),
  'messages',coalesce((select jsonb_agg(jsonb_build_object('id',id,'author_name',author_name,'body',body,'created_at',created_at) order by created_at) from public.nextasx_task_messages where task_id=v_task.id),'[]'::jsonb),
  'attachments',coalesce((select jsonb_agg(jsonb_build_object('id',id,'author_name',author_name,'file_name',file_name,'content_type',content_type,'byte_size',byte_size,'created_at',created_at) order by created_at) from public.nextasx_task_attachments where task_id=v_task.id),'[]'::jsonb)
 );
end $$;

create or replace function public.nextasx_guest_toggle_checklist(p_session_token text,p_id bigint,p_complete boolean)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_session public.nextasx_guest_sessions; v_share public.nextasx_guest_shares; v_row public.nextasx_task_checklist;
begin
 select * into v_session from public.nextasx_guest_sessions where token_hash=encode(extensions.digest(p_session_token,'sha256'),'hex') and expires_at>now();
 select * into v_share from public.nextasx_guest_shares where id=v_session.share_id and revoked_at is null and expires_at>now();
 if v_share.id is null then raise exception 'Unauthorized'; end if;
 update public.nextasx_task_checklist set is_complete=p_complete,completed_by=null,completed_by_name=case when p_complete then v_session.guest_name||' (Guest)' else null end,completed_at=case when p_complete then now() else null end
 where id=p_id and task_id=v_share.task_id returning * into v_row;
 if v_row.id is null then raise exception 'Checklist item not found'; end if;
 return to_jsonb(v_row)-'created_by'-'completed_by'-'position'-'task_id';
end $$;

create or replace function public.nextasx_guest_add_message(p_session_token text,p_body text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_session public.nextasx_guest_sessions; v_share public.nextasx_guest_shares; v_row public.nextasx_task_messages;
begin
 select * into v_session from public.nextasx_guest_sessions where token_hash=encode(extensions.digest(p_session_token,'sha256'),'hex') and expires_at>now();
 select * into v_share from public.nextasx_guest_shares where id=v_session.share_id and revoked_at is null and expires_at>now();
 if v_share.id is null then raise exception 'Unauthorized'; end if;
 if length(trim(p_body))<1 or length(trim(p_body))>2000 then raise exception 'Message must be 1 to 2000 characters'; end if;
 insert into public.nextasx_task_messages(task_id,member_id,author_name,body) values(v_share.task_id,null,v_session.guest_name||' (Guest)',trim(p_body)) returning * into v_row;
 return jsonb_build_object('id',v_row.id,'author_name',v_row.author_name,'body',v_row.body,'created_at',v_row.created_at);
end $$;

create or replace function public.nextasx_guest_add_attachment(p_session_token text,p_file_name text,p_content_type text,p_data_base64 text)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_session public.nextasx_guest_sessions; v_share public.nextasx_guest_shares; v_data bytea; v_row public.nextasx_task_attachments;
begin
 select * into v_session from public.nextasx_guest_sessions where token_hash=encode(extensions.digest(p_session_token,'sha256'),'hex') and expires_at>now();
 select * into v_share from public.nextasx_guest_shares where id=v_session.share_id and revoked_at is null and expires_at>now();
 if v_share.id is null then raise exception 'Unauthorized'; end if;
 v_data:=decode(p_data_base64,'base64'); if octet_length(v_data)>4194304 then raise exception 'File is larger than 4 MB'; end if;
 insert into public.nextasx_task_attachments(task_id,member_id,author_name,file_name,content_type,byte_size,file_data)
 values(v_share.task_id,null,v_session.guest_name||' (Guest)',left(p_file_name,180),left(p_content_type,120),octet_length(v_data),v_data) returning * into v_row;
 return jsonb_build_object('id',v_row.id,'author_name',v_row.author_name,'file_name',v_row.file_name,'content_type',v_row.content_type,'byte_size',v_row.byte_size,'created_at',v_row.created_at);
end $$;

create or replace function public.nextasx_guest_get_attachment(p_session_token text,p_id bigint)
returns jsonb language plpgsql security definer set search_path=''
as $$
declare v_session public.nextasx_guest_sessions; v_share public.nextasx_guest_shares; v_row public.nextasx_task_attachments;
begin
 select * into v_session from public.nextasx_guest_sessions where token_hash=encode(extensions.digest(p_session_token,'sha256'),'hex') and expires_at>now();
 select * into v_share from public.nextasx_guest_shares where id=v_session.share_id and revoked_at is null and expires_at>now();
 if v_share.id is null then raise exception 'Unauthorized'; end if;
 select * into v_row from public.nextasx_task_attachments where id=p_id and task_id=v_share.task_id;
 if v_row.id is null then raise exception 'File not found'; end if;
 return jsonb_build_object('file_name',v_row.file_name,'content_type',v_row.content_type,'data_base64',encode(v_row.file_data,'base64'));
end $$;

revoke execute on function public.nextasx_create_guest_share(text,text,bigint,text,text,timestamptz) from public,authenticated;
revoke execute on function public.nextasx_revoke_guest_share(text,text,bigint) from public,authenticated;
revoke execute on function public.nextasx_guest_login(text,text,text,text) from public,authenticated;
revoke execute on function public.nextasx_guest_task(text) from public,authenticated;
revoke execute on function public.nextasx_guest_toggle_checklist(text,bigint,boolean) from public,authenticated;
revoke execute on function public.nextasx_guest_add_message(text,text) from public,authenticated;
revoke execute on function public.nextasx_guest_add_attachment(text,text,text,text) from public,authenticated;
revoke execute on function public.nextasx_guest_get_attachment(text,bigint) from public,authenticated;
grant execute on function public.nextasx_create_guest_share(text,text,bigint,text,text,timestamptz) to anon;
grant execute on function public.nextasx_revoke_guest_share(text,text,bigint) to anon;
grant execute on function public.nextasx_guest_login(text,text,text,text) to anon;
grant execute on function public.nextasx_guest_task(text) to anon;
grant execute on function public.nextasx_guest_toggle_checklist(text,bigint,boolean) to anon;
grant execute on function public.nextasx_guest_add_message(text,text) to anon;
grant execute on function public.nextasx_guest_add_attachment(text,text,text,text) to anon;
grant execute on function public.nextasx_guest_get_attachment(text,bigint) to anon;
