"use client";
import{useEffect,useState}from"react";import{useParams}from"next/navigation";
type Task={id:number;title:string;description:string;assignee:string;category:string;location:string;priority:string;status:string;due_date:string};
type Item={id:number;body:string;is_complete:boolean;completed_by_name:string|null;completed_at:string|null};
type Message={id:number;author_name:string;body:string;created_at:string};
type Attachment={id:number;author_name:string;file_name:string;content_type:string;byte_size:number};
type Data={guest_name:string;task:Task;checklist:Item[];messages:Message[];attachments:Attachment[]};
export default function SharedTask(){
 const token=String(useParams().token||""),[data,setData]=useState<Data|null>(null),[name,setName]=useState(""),[pin,setPin]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 async function load(){setBusy(true);const r=await fetch(`/api/guest/${token}/task`,{cache:"no-store"});setBusy(false);if(r.ok)setData(await r.json());else setData(null)}
 useEffect(()=>{load()},[token]);
 async function unlock(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const r=await fetch(`/api/guest/${token}/unlock`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,pin})}),d=await r.json();setBusy(false);if(!r.ok){setError(d.error||"Access could not be opened.");return}await load()}
 async function toggle(item:Item,complete:boolean){if(!data)return;setData({...data,checklist:data.checklist.map(x=>x.id===item.id?{...x,is_complete:complete,completed_by_name:complete?`${data.guest_name} (Guest)`:null}:x)});const r=await fetch(`/api/guest/${token}/checklist/${item.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({complete})});if(!r.ok){alert("That checklist change could not be saved.");load()}}
 async function postMessage(e:React.FormEvent){e.preventDefault();if(!message.trim()||!data)return;setBusy(true);const r=await fetch(`/api/guest/${token}/messages`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({body:message})}),d=await r.json();setBusy(false);if(!r.ok){alert(d.error||"Message could not be posted.");return}setData({...data,messages:[...data.messages,d.message]});setMessage("")}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||!data)return;setBusy(true);const form=new FormData();form.append("file",file);const r=await fetch(`/api/guest/${token}/attachments`,{method:"POST",body:form}),d=await r.json();setBusy(false);if(!r.ok){alert(d.error||"File could not be uploaded.");return}setData({...data,attachments:[...data.attachments,d.attachment]});e.target.value=""}
 if(busy&&!data)return <main className="guestShell"><div className="guestBrand"><div className="mini">NX</div><b>NEXTASX</b></div><section className="guestCard"><p>Opening shared task…</p></section></main>;
 if(!data)return <main className="guestShell"><div className="guestBrand"><div className="mini">NX</div><b>NEXTASX</b></div><section className="guestCard guestLogin"><h1>Shared task</h1><p>S2 Farms shared one task with you. Enter your name and the PIN they provided.</p><form onSubmit={unlock}><label>Your name<input autoFocus required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>Access PIN<input required inputMode="numeric" pattern="[0-9]*" minLength={4} maxLength={6} value={pin} onChange={e=>setPin(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Opening…":"Open shared task"}</button></form><small>You will only be able to access this individual task.</small></section></main>;
 const done=data.checklist.filter(x=>x.is_complete).length;
 return <main className="guestShell"><div className="guestBrand"><div className="mini">NX</div><div><b>NEXTASX</b><span>Shared by S2 Farms</span></div></div><section className="guestCard"><div className="guestTaskHead"><div><span className="guestLabel">SHARED TASK</span><h1>{data.task.title}</h1></div><span className={`statusPill status-${data.task.status.toLowerCase().replace(" ","-")}`}>{data.task.status}</span></div>{data.task.description&&<p className="guestDescription">{data.task.description}</p>}<div className="guestMeta"><span>👤 {data.task.assignee}</span><span>🏷 {data.task.category}</span>{data.task.location&&<span>📍 {data.task.location}</span>}{data.task.due_date&&<span>🗓 {data.task.due_date}</span>}</div><div className="guestWelcome">Working as <b>{data.guest_name}</b></div></section>
 <section className="guestCard"><div className="checklistTitle"><h2>Checklist</h2><b>{done} of {data.checklist.length} complete</b></div>{data.checklist.length?<div className="guestChecklist">{data.checklist.map(item=><label className={item.is_complete?"guestCheck done":"guestCheck"} key={item.id}><input type="checkbox" checked={item.is_complete} onChange={e=>toggle(item,e.target.checked)}/><span><b>{item.body}</b>{item.is_complete&&<small>Completed by {item.completed_by_name}</small>}</span></label>)}</div>:<p className="quiet">No checklist items were added.</p>}</section>
 <section className="guestCard"><h2>Conversation</h2>{data.messages.length?<div className="guestMessages">{data.messages.map(m=><div className="message" key={m.id}><b>{m.author_name}</b><span>{new Date(m.created_at).toLocaleString()}</span><p>{m.body}</p></div>)}</div>:<p className="quiet">No messages yet.</p>}<form className="messageForm" onSubmit={postMessage}><textarea required maxLength={2000} rows={3} placeholder="Add an update or question…" value={message} onChange={e=>setMessage(e.target.value)}/><button disabled={busy}>Post message</button></form></section>
 <section className="guestCard"><div className="filesHead"><h2>Photos and documents</h2><label className="uploadButton">＋ Add file<input type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.csv,.txt" onChange={upload}/></label></div>{data.attachments.length?<div className="fileList">{data.attachments.map(a=><a key={a.id} href={`/api/guest/${token}/attachments/${a.id}`} target="_blank" rel="noreferrer"><span>{a.content_type.startsWith("image/")?"📷":"📄"}</span><div><b>{a.file_name}</b><small>{a.author_name} · {(a.byte_size/1024).toFixed(0)} KB</small></div></a>)}</div>:<p className="quiet">No files attached yet.</p>}</section></main>
}
